// Ward (phường/xã) list for TP. Hồ Chí Minh — old HCMC territory only.
// Source: ThangLeQuoc/vietnamese-provinces-database (Decree 30/2026/QH16).
// Excludes wards from merged Bình Dương (codes <26506) and Bà Rịa-Vũng Tàu (codes 26506-26732).

export const HCMC_WARDS = [
  'Phường An Đông',
  'Phường An Hội Đông',
  'Phường An Hội Tây',
  'Phường An Khánh',
  'Phường An Lạc',
  'Phường An Nhơn',
  'Phường An Phú Đông',
  'Phường Bàn Cờ',
  'Phường Bảy Hiền',
  'Phường Bến Thành',
  'Phường Bình Đông',
  'Phường Bình Hưng Hoà',
  'Phường Bình Lợi Trung',
  'Phường Bình Phú',
  'Phường Bình Quới',
  'Phường Bình Tân',
  'Phường Bình Tây',
  'Phường Bình Thạnh',
  'Phường Bình Thới',
  'Phường Bình Tiên',
  'Phường Bình Trị Đông',
  'Phường Bình Trưng',
  'Phường Cát Lái',
  'Phường Cầu Kiệu',
  'Phường Cầu Ông Lãnh',
  'Phường Chánh Hưng',
  'Phường Chợ Lớn',
  'Phường Chợ Quán',
  'Phường Diên Hồng',
  'Phường Đông Hưng Thuận',
  'Phường Đức Nhuận',
  'Phường Gia Định',
  'Phường Gò Vấp',
  'Phường Hạnh Thông',
  'Phường Hiệp Bình',
  'Phường Hoà Bình',
  'Phường Hoà Hưng',
  'Phường Khánh Hội',
  'Phường Linh Xuân',
  'Phường Long Bình',
  'Phường Long Phước',
  'Phường Long Trường',
  'Phường Minh Phụng',
  'Phường Nhiêu Lộc',
  'Phường Phú Định',
  'Phường Phú Lâm',
  'Phường Phú Nhuận',
  'Phường Phú Thạnh',
  'Phường Phú Thọ',
  'Phường Phú Thọ Hoà',
  'Phường Phú Thuận',
  'Phường Phước Long',
  'Phường Sài Gòn',
  'Phường Tam Bình',
  'Phường Tăng Nhơn Phú',
  'Phường Tân Bình',
  'Phường Tân Định',
  'Phường Tân Hoà',
  'Phường Tân Hưng',
  'Phường Tân Mỹ',
  'Phường Tân Phú',
  'Phường Tân Sơn',
  'Phường Tân Sơn Hoà',
  'Phường Tân Sơn Nhất',
  'Phường Tân Sơn Nhì',
  'Phường Tân Tạo',
  'Phường Tân Thới Hiệp',
  'Phường Tân Thuận',
  'Phường Tây Thạnh',
  'Phường Thạnh Mỹ Tây',
  'Phường Thông Tây Hội',
  'Phường Thới An',
  'Phường Thủ Đức',
  'Phường Trung Mỹ Tây',
  'Phường Vĩnh Hội',
  'Phường Vườn Lài',
  'Phường Xóm Chiếu',
  'Phường Xuân Hoà',
  'Xã An Nhơn Tây',
  'Xã An Thới Đông',
  'Xã Bà Điểm',
  'Xã Bình Chánh',
  'Xã Bình Hưng',
  'Xã Bình Khánh',
  'Xã Bình Lợi',
  'Xã Bình Mỹ',
  'Xã Cần Giờ',
  'Xã Củ Chi',
  'Xã Đông Thạnh',
  'Xã Hiệp Phước',
  'Xã Hóc Môn',
  'Xã Hưng Long',
  'Xã Nhà Bè',
  'Xã Nhuận Đức',
  'Xã Phú Hoà Đông',
  'Xã Tân An Hội',
  'Xã Tân Nhựt',
  'Xã Tân Vĩnh Lộc',
  'Xã Thái Mỹ',
  'Xã Thạnh An',
  'Xã Vĩnh Lộc',
  'Xã Xuân Thới Sơn',
] as const;

export type HcmcWard = (typeof HCMC_WARDS)[number];
